name: centipede-environment

on:
  schedule:
    # trigger the workflow on the every sunday at 2 am UTC
    - cron: '0 2 * * 6'
  workflow_dispatch:

jobs:
  docker-build:
    # environment: docker_deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        id: push
        with:
          push: true
          context: util/container_env
          tags: ghcr.io/yanzhaow/centipede_env:latest

      # - name: Generate artifact attestation
      #   uses: actions/attest@v4
      #   with:
      #     subject-name: ghcr.io/yanzhaow/centipede_env
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
