name: Coverage
on:
  schedule:
  # trigger the workflow on the every 2 am UTC
  - cron: '00 02 * * *'
  pull_request_target:
    branches:
      - master
  push:
    branches:
      - master
permissions: write-all

jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: codacy
    container:
      image: ghcr.io/yanzhaow/centipede_env:latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: 'true'
          ref: "${{ github.event.pull_request.head.sha }}"

      - name: pre-build
        uses: './.github/actions/pre_build_config'

      - name: build-test-submit
        run: |
          dnf install -y gcovr
          cmake --workflow --preset coverage
          gcovr --clover --clover-pretty --exclude ".*test.*\.cpp" --output=clover.xml
        shell: bash
      - name: submit report
        if: github.event_name == 'pull_request_target'
        run: |
          auth="--project-token ${{ secrets.CODACY_PROJECT_TOKEN }}"
          commit_uuid="--commit-uuid ${{ github.event.pull_request.head.sha }}"
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report $auth $commit_uuid -r clover.xml
      - name: Run codacy-coverage-reporter
        if: github.event_name == 'push'
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: clover.xml
          # or a comma-separated list for multiple reports
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>
